version: '3.9'

services:
  timelog.web:
    image: ${DOCKER_REGISTRY-}timelog.webapp
    build:
      context: .
      dockerfile: Timelog.WebApp/Dockerfile    
  timelog.api:
    image: ${DOCKER_REGISTRY-}timelog.api
    build:
      context: .
      dockerfile: Timelog.Api/Dockerfile  
  
