CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

CREATE TABLE "ActivityTypes" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NULL,
    "Description" text NULL,
    "UniqId" uuid NOT NULL,
    "UserUniqId" uuid NOT NULL,
    CONSTRAINT "PK_ActivityTypes" PRIMARY KEY ("Id")
);

CREATE TABLE "Projects" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NULL,
    "Description" text NULL,
    "UniqId" uuid NOT NULL,
    "UserUniqId" uuid NOT NULL,
    CONSTRAINT "PK_Projects" PRIMARY KEY ("Id")
);

CREATE TABLE "UserActivities" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "StartTime" timestamp with time zone NOT NULL,
    "EndTime" timestamp with time zone NOT NULL,
    "Status" integer NOT NULL,
    "Title" text NULL,
    "Comment" text NULL,
    "ProjectId" bigint NOT NULL,
    "ActivityTypeId" bigint NOT NULL,
    "UniqId" uuid NOT NULL,
    "UserUniqId" uuid NOT NULL,
    CONSTRAINT "PK_UserActivities" PRIMARY KEY ("Id")
);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20220324101629_initTimlog', '6.0.3');

COMMIT;

START TRANSACTION;

ALTER TABLE "UserActivities" ALTER COLUMN "StartTime" TYPE timestamp without time zone;

ALTER TABLE "UserActivities" ALTER COLUMN "EndTime" TYPE timestamp without time zone;

CREATE INDEX "IX_UserActivities_ProjectId" ON "UserActivities" ("ProjectId");

ALTER TABLE "UserActivities" ADD CONSTRAINT "FK_UserActivities_Projects_ProjectId" FOREIGN KEY ("ProjectId") REFERENCES "Projects" ("Id") ON DELETE CASCADE;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20220325062910_PersonNav', '6.0.3');

COMMIT;

START TRANSACTION;

CREATE INDEX "IX_UserActivities_ActivityTypeId" ON "UserActivities" ("ActivityTypeId");

ALTER TABLE "UserActivities" ADD CONSTRAINT "FK_UserActivities_ActivityTypes_ActivityTypeId" FOREIGN KEY ("ActivityTypeId") REFERENCES "ActivityTypes" ("Id") ON DELETE CASCADE;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20220328034046_TimelogActivityAddTypeReferens', '6.0.3');

COMMIT;

