POST https://localhost:7148/api/Projects
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJlNDZjODAwYy01NmZjLTQzZTQtODRmNS01ODcxZjI3ODY3NTAiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoieGFuQHhhbi5ydSIsImp0aSI6ImQxOWI5MThlLTcxYjAtNDEzNi1iNTRlLWUwN2UzZmQ3MmYwZSIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL25hbWVpZGVudGlmaWVyIjoiZTQ2YzgwMGMtNTZmYy00M2U0LTg0ZjUtNTg3MWYyNzg2NzUwIiwiZXhwIjoxNjUyMjMwMjQwLCJpc3MiOiJodHRwczovL2xvY2FsaG9zdDo1MDAwIiwiYXVkIjoiaHR0cHM6Ly9sb2NhbGhvc3Q6NTAwMCJ9.ToFMoc4GWpQly6XkGW6tUfOqsrEb2vtsVl4Ys9uYCm8
Content-Type: application/json

{
    "Name" : "TestProject",
    "Description" : "-"
}