GET https://localhost:7148/api/Projects
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJlNDZjODAwYy01NmZjLTQzZTQtODRmNS01ODcxZjI3ODY3NTAiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoieGFuQHhhbi5ydSIsImp0aSI6IjUxYzYwMGEwLTcyMWItNDQ3MS1iNTUxLTg0ZGEyNmRlMTI4ZiIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL25hbWVpZGVudGlmaWVyIjoiZTQ2YzgwMGMtNTZmYy00M2U0LTg0ZjUtNTg3MWYyNzg2NzUwIiwiZXhwIjoxNjUxOTA1MTQ2LCJpc3MiOiJodHRwczovL2xvY2FsaG9zdDo1MDAwIiwiYXVkIjoiaHR0cHM6Ly9sb2NhbGhvc3Q6NTAwMCJ9.3leAU9M8BSNkngtvXz0xUvUPcajY_ZFjrI8g1oQGwjs